server:
  host: 127.0.0.1
  port: 9000
  heartbeat_interval: 30
  account_update_interval: 15
copy_rules:
- id: 5108e661
  name: RuleExtractors
  enabled: true
  source_terminal_path: C:\MetaTrader4
  destinations:
  - terminal_path: C:\MetaTrader5
    size_mode: proportional
    size_value: 100.0
    size_by_magic: {}
  magic_numbers: []
  symbol_map: {}
